// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5YDxRFLhGOXSCHD3GSiqjgby2b4Yj5iM',
    appId: '1:273784309408:android:4858272fc2e8ea86016bc5',
    messagingSenderId: '273784309408',
    projectId: 'chatapp-f0a73',
    storageBucket: 'chatapp-f0a73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkPDo3ItaMMQpKi8Mfpj8xHTalYavBr7g',
    appId: '1:273784309408:ios:a89dedd1b6d82b10016bc5',
    messagingSenderId: '273784309408',
    projectId: 'chatapp-f0a73',
    storageBucket: 'chatapp-f0a73.appspot.com',
    iosBundleId: 'com.example.firebaseChatDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkPDo3ItaMMQpKi8Mfpj8xHTalYavBr7g',
    appId: '1:273784309408:ios:c9a36f01f147d318016bc5',
    messagingSenderId: '273784309408',
    projectId: 'chatapp-f0a73',
    storageBucket: 'chatapp-f0a73.appspot.com',
    iosBundleId: 'com.example.firebaseChatDemo.RunnerTests',
  );
}
